import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["900", "200", "100"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Luxury Cars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-mainWhite`}>
        <div className="mx-auto">{children}</div>
      </body>
    </html>
  );
}
